using RegisterPanel.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace RegisterPanel.Infrastructure.Persistence.Configurations;

public sealed class AdminSettingsConfiguration : IEntityTypeConfiguration<AdminSettings>
{
    public void Configure(EntityTypeBuilder<AdminSettings> builder)
    {
        builder.ToTable("admin_settings");

        builder.HasKey(x => x.Id);

        // Fixed Id = 1; never auto-generated by the database
        builder.Property(x => x.Id)
               .ValueGeneratedNever();

        builder.Property(x => x.MaxSimultaneousTrainers)
               .IsRequired();

        builder.Property(x => x.MaxSimultaneousClientsPerTrainer)
               .IsRequired();

        builder.Property(x => x.MinHoursBeforeCancellation)
               .IsRequired();

        builder.Property(x => x.AllowLateCancelWithPenalty)
               .IsRequired();

        builder.Property(x => x.UpdatedAt)
               .IsRequired()
               .HasColumnType("timestamp with time zone");

        builder.Property(x => x.UpdatedByUserId)
               .IsRequired()
               .HasMaxLength(450);
    }
}
